import type {
  User,
  Role,
  Application,
  LoginActivity,
  Session,
  SSOProvider,
  EmailTemplate,
  PermissionMatrix,
} from "./types";

const now = new Date().toISOString();
const daysAgo = (d: number) => new Date(Date.now() - d * 86400000).toISOString();
const hoursAgo = (h: number) => new Date(Date.now() - h * 3600000).toISOString();
const minsAgo = (m: number) => new Date(Date.now() - m * 60000).toISOString();

const adminPerms: PermissionMatrix = {
  users: { create: true, read: true, update: true, delete: true },
  roles: { create: true, read: true, update: true, delete: true },
  applications: { create: true, read: true, update: true, delete: true },
  reports: { create: true, read: true, update: true, delete: true },
  settings: { create: true, read: true, update: true, delete: true },
  audit_logs: { create: false, read: true, update: false, delete: false },
};

const userPerms: PermissionMatrix = {
  users: { create: false, read: true, update: false, delete: false },
  roles: { create: false, read: true, update: false, delete: false },
  applications: { create: false, read: true, update: false, delete: false },
  reports: { create: false, read: true, update: false, delete: false },
  settings: { create: false, read: true, update: true, delete: false },
  audit_logs: { create: false, read: true, update: false, delete: false },
};

const viewerPerms: PermissionMatrix = {
  users: { create: false, read: true, update: false, delete: false },
  roles: { create: false, read: true, update: false, delete: false },
  applications: { create: false, read: true, update: false, delete: false },
  reports: { create: false, read: true, update: false, delete: false },
  settings: { create: false, read: false, update: false, delete: false },
  audit_logs: { create: false, read: true, update: false, delete: false },
};

const superAdminPerms: PermissionMatrix = {
  users: { create: true, read: true, update: true, delete: true },
  roles: { create: true, read: true, update: true, delete: true },
  applications: { create: true, read: true, update: true, delete: true },
  reports: { create: true, read: true, update: true, delete: true },
  settings: { create: true, read: true, update: true, delete: true },
  audit_logs: { create: true, read: true, update: true, delete: true },
};

export const initialRoles: Role[] = [
  {
    id: "role-1",
    name: "Super Admin",
    description: "Full system access with all permissions",
    permissions: superAdminPerms,
    userCount: 1,
    createdAt: daysAgo(90),
    updatedAt: daysAgo(10),
    color: "purple",
  },
  {
    id: "role-2",
    name: "Admin",
    description: "Administrative access to manage users and applications",
    permissions: adminPerms,
    userCount: 3,
    createdAt: daysAgo(80),
    updatedAt: daysAgo(5),
    color: "blue",
  },
  {
    id: "role-3",
    name: "User",
    description: "Standard user access to assigned applications",
    permissions: userPerms,
    userCount: 45,
    createdAt: daysAgo(70),
    updatedAt: daysAgo(2),
    color: "teal",
  },
  {
    id: "role-4",
    name: "Viewer",
    description: "Read-only access to reports and dashboards",
    permissions: viewerPerms,
    userCount: 12,
    createdAt: daysAgo(60),
    updatedAt: daysAgo(7),
    color: "gray",
  },
];

export const initialApplications: Application[] = [
  {
    id: "app-1",
    name: "Slack",
    description: "Team communication and collaboration platform",
    icon: "MessageCircle",
    category: "Communication",
    status: "active",
    url: "https://slack.com",
    baseUrl: "https://slack.com",
    callbackUrl: "https://slack.com/oauth/callback",
    secretKey: "sk_live_abc123def456ghi789",
    clientId: "client_slack_001",
    allowedRoles: ["super_admin", "admin", "user"],
    lastAccessed: hoursAgo(2),
    createdAt: daysAgo(60),
    updatedAt: daysAgo(5),
  },
  {
    id: "app-2",
    name: "GitHub",
    description: "Code hosting and version control platform",
    icon: "Github",
    category: "Development",
    status: "active",
    url: "https://github.com",
    baseUrl: "https://github.com",
    callbackUrl: "https://github.com/oauth/callback",
    secretKey: "sk_live_xyz789uvw456rst123",
    clientId: "client_github_002",
    allowedRoles: ["super_admin", "admin", "user"],
    lastAccessed: hoursAgo(1),
    createdAt: daysAgo(55),
    updatedAt: daysAgo(3),
  },
  {
    id: "app-3",
    name: "Jira",
    description: "Project management and issue tracking",
    icon: "ClipboardList",
    category: "Project Management",
    status: "active",
    url: "https://atlassian.com",
    baseUrl: "https://atlassian.net",
    callbackUrl: "https://atlassian.net/oauth/callback",
    secretKey: "sk_live_jira567mno890pqr123",
    clientId: "client_jira_003",
    allowedRoles: ["super_admin", "admin", "user", "viewer"],
    lastAccessed: hoursAgo(5),
    createdAt: daysAgo(50),
    updatedAt: daysAgo(1),
  },
  {
    id: "app-4",
    name: "Google Analytics",
    description: "Web analytics and reporting service",
    icon: "BarChart3",
    category: "Analytics",
    status: "active",
    url: "https://analytics.google.com",
    baseUrl: "https://analytics.google.com",
    callbackUrl: "https://analytics.google.com/oauth/callback",
    secretKey: "sk_live_ga_analytics_key_999",
    clientId: "client_ga_004",
    allowedRoles: ["super_admin", "admin", "viewer"],
    lastAccessed: daysAgo(1),
    createdAt: daysAgo(45),
    updatedAt: daysAgo(8),
  },
  {
    id: "app-5",
    name: "Figma",
    description: "Collaborative interface design tool",
    icon: "Palette",
    category: "Design",
    status: "active",
    url: "https://figma.com",
    baseUrl: "https://figma.com",
    callbackUrl: "https://figma.com/oauth/callback",
    secretKey: "sk_live_figma_design_key_555",
    clientId: "client_figma_005",
    allowedRoles: ["super_admin", "admin", "user"],
    lastAccessed: hoursAgo(3),
    createdAt: daysAgo(40),
    updatedAt: daysAgo(4),
  },
  {
    id: "app-6",
    name: "Salesforce",
    description: "Customer relationship management platform",
    icon: "Cloud",
    category: "CRM",
    status: "active",
    url: "https://salesforce.com",
    baseUrl: "https://salesforce.com",
    callbackUrl: "https://salesforce.com/oauth/callback",
    secretKey: "sk_live_sf_crm_key_444",
    clientId: "client_sf_006",
    allowedRoles: ["super_admin", "admin"],
    lastAccessed: daysAgo(2),
    createdAt: daysAgo(35),
    updatedAt: daysAgo(6),
  },
  {
    id: "app-7",
    name: "Zoom",
    description: "Video conferencing and webinar platform",
    icon: "Video",
    category: "Communication",
    status: "maintenance",
    url: "https://zoom.us",
    baseUrl: "https://zoom.us",
    callbackUrl: "https://zoom.us/oauth/callback",
    secretKey: "sk_live_zoom_video_key_333",
    clientId: "client_zoom_007",
    allowedRoles: ["super_admin", "admin", "user", "viewer"],
    lastAccessed: daysAgo(3),
    createdAt: daysAgo(30),
    updatedAt: daysAgo(0),
  },
  {
    id: "app-8",
    name: "AWS Console",
    description: "Amazon Web Services management console",
    icon: "Hexagon",
    category: "Infrastructure",
    status: "active",
    url: "https://console.aws.amazon.com",
    baseUrl: "https://console.aws.amazon.com",
    callbackUrl: "https://console.aws.amazon.com/oauth/callback",
    secretKey: "sk_live_aws_infra_key_222",
    clientId: "client_aws_008",
    allowedRoles: ["super_admin", "admin"],
    lastAccessed: hoursAgo(6),
    createdAt: daysAgo(25),
    updatedAt: daysAgo(2),
  },
];

export const initialUsers: User[] = [
  {
    id: "user-1",
    email: "admin@example.com",
    firstName: "Alice",
    lastName: "Johnson",
    role: "super_admin",
    status: "active",
    phone: "+1 (555) 000-0001",
    department: "IT",
    twoFactorEnabled: true,
    password: "Admin@123",
    favoriteApps: ["app-1", "app-2", "app-5"],
    lastLogin: hoursAgo(2),
    lastLoginIp: "192.168.1.1",
    createdAt: daysAgo(90),
    updatedAt: daysAgo(1),
    sessionCount: 2,
    notificationsEnabled: true,
    emailNotifications: true,
    theme: "dark",
    language: "en",
    timezone: "America/New_York",
  },
  {
    id: "user-2",
    email: "bob@example.com",
    firstName: "Bob",
    lastName: "Smith",
    role: "admin",
    status: "active",
    phone: "+1 (555) 000-0002",
    department: "Engineering",
    twoFactorEnabled: false,
    password: "Admin@123",
    favoriteApps: ["app-2", "app-3"],
    lastLogin: hoursAgo(5),
    lastLoginIp: "192.168.1.2",
    createdAt: daysAgo(80),
    updatedAt: daysAgo(2),
    sessionCount: 1,
    notificationsEnabled: true,
    emailNotifications: false,
    theme: "light",
    language: "en",
    timezone: "America/Chicago",
  },
  {
    id: "user-3",
    email: "carol@example.com",
    firstName: "Carol",
    lastName: "Williams",
    role: "user",
    status: "active",
    phone: "+1 (555) 000-0003",
    department: "Marketing",
    twoFactorEnabled: true,
    password: "User@123",
    favoriteApps: ["app-1", "app-5"],
    lastLogin: daysAgo(1),
    lastLoginIp: "192.168.1.3",
    createdAt: daysAgo(70),
    updatedAt: daysAgo(3),
    sessionCount: 1,
    notificationsEnabled: true,
    emailNotifications: true,
    theme: "system",
    language: "en",
    timezone: "America/Los_Angeles",
  },
  {
    id: "user-4",
    email: "dave@example.com",
    firstName: "Dave",
    lastName: "Brown",
    role: "user",
    status: "inactive",
    phone: "+1 (555) 000-0004",
    department: "Sales",
    twoFactorEnabled: false,
    password: "User@123",
    favoriteApps: [],
    lastLogin: daysAgo(14),
    lastLoginIp: "192.168.1.4",
    createdAt: daysAgo(60),
    updatedAt: daysAgo(14),
    sessionCount: 0,
    notificationsEnabled: false,
    emailNotifications: false,
    theme: "light",
    language: "en",
    timezone: "Europe/London",
  },
  {
    id: "user-5",
    email: "eve@example.com",
    firstName: "Eve",
    lastName: "Davis",
    role: "viewer",
    status: "active",
    phone: "+1 (555) 000-0005",
    department: "Finance",
    twoFactorEnabled: false,
    password: "View@123",
    favoriteApps: ["app-4"],
    lastLogin: hoursAgo(8),
    lastLoginIp: "192.168.1.5",
    createdAt: daysAgo(50),
    updatedAt: daysAgo(4),
    sessionCount: 1,
    notificationsEnabled: true,
    emailNotifications: true,
    theme: "light",
    language: "en",
    timezone: "Asia/Tokyo",
  },
  {
    id: "user-6",
    email: "frank@example.com",
    firstName: "Frank",
    lastName: "Wilson",
    role: "admin",
    status: "suspended",
    phone: "+1 (555) 000-0006",
    department: "IT",
    twoFactorEnabled: false,
    password: "Admin@123",
    favoriteApps: [],
    lastLogin: daysAgo(30),
    lastLoginIp: "192.168.1.6",
    createdAt: daysAgo(45),
    updatedAt: daysAgo(30),
    sessionCount: 0,
    notificationsEnabled: false,
    emailNotifications: false,
    theme: "dark",
    language: "en",
    timezone: "Europe/Paris",
  },
];

export const initialLoginActivity: LoginActivity[] = [
  {
    id: "la-1",
    userId: "user-1",
    userEmail: "admin@example.com",
    userName: "Alice Johnson",
    applicationId: "app-1",
    applicationName: "Slack",
    status: "success",
    ip: "192.168.1.1",
    location: "New York, US",
    device: "Desktop",
    browser: "Chrome 120",
    timestamp: minsAgo(30),
  },
  {
    id: "la-2",
    userId: "user-2",
    userEmail: "bob@example.com",
    userName: "Bob Smith",
    applicationId: "app-2",
    applicationName: "GitHub",
    status: "success",
    ip: "192.168.1.2",
    location: "Chicago, US",
    device: "Desktop",
    browser: "Firefox 121",
    timestamp: hoursAgo(1),
  },
  {
    id: "la-3",
    userId: "user-3",
    userEmail: "carol@example.com",
    userName: "Carol Williams",
    status: "failed",
    ip: "10.0.0.15",
    location: "Los Angeles, US",
    device: "Mobile",
    browser: "Safari 17",
    timestamp: hoursAgo(2),
    failureReason: "Invalid password",
  },
  {
    id: "la-4",
    userId: "user-1",
    userEmail: "admin@example.com",
    userName: "Alice Johnson",
    applicationId: "app-5",
    applicationName: "Figma",
    status: "success",
    ip: "192.168.1.1",
    location: "New York, US",
    device: "Desktop",
    browser: "Chrome 120",
    timestamp: hoursAgo(3),
  },
  {
    id: "la-5",
    userId: "user-6",
    userEmail: "frank@example.com",
    userName: "Frank Wilson",
    status: "blocked",
    ip: "203.0.113.42",
    location: "Unknown, XX",
    device: "Desktop",
    browser: "Unknown",
    timestamp: hoursAgo(4),
    failureReason: "Account suspended",
  },
  {
    id: "la-6",
    userId: "user-5",
    userEmail: "eve@example.com",
    userName: "Eve Davis",
    applicationId: "app-4",
    applicationName: "Google Analytics",
    status: "success",
    ip: "192.168.1.5",
    location: "Tokyo, JP",
    device: "Desktop",
    browser: "Chrome 120",
    timestamp: hoursAgo(5),
  },
  {
    id: "la-7",
    userId: "user-4",
    userEmail: "dave@example.com",
    userName: "Dave Brown",
    status: "failed",
    ip: "172.16.0.10",
    location: "London, UK",
    device: "Tablet",
    browser: "Edge 120",
    timestamp: hoursAgo(8),
    failureReason: "Account inactive",
  },
  {
    id: "la-8",
    userId: "user-2",
    userEmail: "bob@example.com",
    userName: "Bob Smith",
    applicationId: "app-3",
    applicationName: "Jira",
    status: "success",
    ip: "192.168.1.2",
    location: "Chicago, US",
    device: "Desktop",
    browser: "Firefox 121",
    timestamp: hoursAgo(10),
  },
  {
    id: "la-9",
    userId: "user-3",
    userEmail: "carol@example.com",
    userName: "Carol Williams",
    applicationId: "app-1",
    applicationName: "Slack",
    status: "success",
    ip: "192.168.1.3",
    location: "Los Angeles, US",
    device: "Mobile",
    browser: "Safari 17",
    timestamp: daysAgo(1),
  },
  {
    id: "la-10",
    userId: "user-1",
    userEmail: "admin@example.com",
    userName: "Alice Johnson",
    applicationId: "app-8",
    applicationName: "AWS Console",
    status: "success",
    ip: "192.168.1.1",
    location: "New York, US",
    device: "Desktop",
    browser: "Chrome 120",
    timestamp: daysAgo(1),
  },
  {
    id: "la-11",
    userId: "user-5",
    userEmail: "eve@example.com",
    userName: "Eve Davis",
    status: "failed",
    ip: "198.51.100.99",
    location: "Tokyo, JP",
    device: "Mobile",
    browser: "Chrome Mobile",
    timestamp: daysAgo(2),
    failureReason: "Invalid 2FA code",
  },
  {
    id: "la-12",
    userId: "user-2",
    userEmail: "bob@example.com",
    userName: "Bob Smith",
    applicationId: "app-2",
    applicationName: "GitHub",
    status: "success",
    ip: "192.168.1.2",
    location: "Chicago, US",
    device: "Desktop",
    browser: "Firefox 121",
    timestamp: daysAgo(2),
  },
];

export const initialSessions: Session[] = [
  {
    id: "sess-1",
    userId: "user-1",
    device: "Desktop",
    browser: "Chrome 120",
    os: "macOS Sonoma",
    ip: "192.168.1.1",
    location: "New York, US",
    lastActive: minsAgo(5),
    createdAt: hoursAgo(2),
    isCurrent: true,
  },
  {
    id: "sess-2",
    userId: "user-1",
    device: "Mobile",
    browser: "Safari 17",
    os: "iOS 17",
    ip: "10.0.0.50",
    location: "New York, US",
    lastActive: hoursAgo(1),
    createdAt: daysAgo(1),
    isCurrent: false,
  },
];

export const initialSSOProviders: SSOProvider[] = [
  {
    id: "sso-1",
    name: "Google",
    type: "oauth2",
    enabled: true,
    clientId: "google-client-id-12345.apps.googleusercontent.com",
    clientSecret: "GOCSPX-google_secret_key",
    authorizationUrl: "https://accounts.google.com/o/oauth2/v2/auth",
    tokenUrl: "https://oauth2.googleapis.com/token",
    userInfoUrl: "https://www.googleapis.com/oauth2/v2/userinfo",
    scopes: ["openid", "email", "profile"],
    lastTested: hoursAgo(3),
    testStatus: "success",
  },
  {
    id: "sso-2",
    name: "Microsoft Azure AD",
    type: "oidc",
    enabled: true,
    clientId: "azure-client-id-abcdef-123456",
    clientSecret: "azure_secret_xxxxxxxxxxxxx",
    authorizationUrl: "https://login.microsoftonline.com/tenant/oauth2/v2.0/authorize",
    tokenUrl: "https://login.microsoftonline.com/tenant/oauth2/v2.0/token",
    userInfoUrl: "https://graph.microsoft.com/oidc/userinfo",
    scopes: ["openid", "email", "profile", "offline_access"],
    lastTested: daysAgo(1),
    testStatus: "success",
  },
  {
    id: "sso-3",
    name: "Okta SAML",
    type: "saml",
    enabled: false,
    clientId: "okta-entity-id",
    clientSecret: "",
    authorizationUrl: "",
    tokenUrl: "",
    userInfoUrl: "",
    scopes: [],
    entityId: "https://company.okta.com",
    ssoUrl: "https://company.okta.com/app/sso/saml",
    certificate: "-----BEGIN CERTIFICATE-----\nMIIDXTCCAkWgAwIBAgIJAKlX...\n-----END CERTIFICATE-----",
    lastTested: daysAgo(7),
    testStatus: "failed",
  },
];

export const initialEmailTemplates: EmailTemplate[] = [
  {
    id: "tpl-1",
    name: "Welcome Email",
    type: "welcome",
    subject: "Welcome to {{company_name}}, {{user_name}}!",
    body: `Dear {{user_name}},

Welcome to {{company_name}}! Your account has been successfully created.

You can now access all your assigned applications through our Single Sign-On portal.

To get started, please log in at: {{login_url}}

Your account details:
- Email: {{user_email}}
- Role: {{user_role}}

If you have any questions, please contact our support team.

Best regards,
The {{company_name}} Team`,
    variables: ["company_name", "user_name", "user_email", "user_role", "login_url"],
    enabled: true,
    lastUpdated: daysAgo(5),
  },
  {
    id: "tpl-2",
    name: "Password Reset",
    type: "password_reset",
    subject: "Reset Your Password - {{company_name}}",
    body: `Hi {{user_name}},

We received a request to reset your password for your {{company_name}} account.

Click the link below to reset your password (expires in 24 hours):
{{reset_url}}

If you didn't request this, please ignore this email or contact support if you have concerns.

Security tip: Never share your password with anyone.

Best regards,
The {{company_name}} Security Team`,
    variables: ["company_name", "user_name", "reset_url"],
    enabled: true,
    lastUpdated: daysAgo(3),
  },
  {
    id: "tpl-3",
    name: "Email Verification",
    type: "email_verification",
    subject: "Verify Your Email - {{company_name}}",
    body: `Hi {{user_name}},

Please verify your email address to complete your account registration.

Your verification code is: {{verification_code}}

Or click here to verify: {{verify_url}}

This code expires in 24 hours.

Best regards,
{{company_name}}`,
    variables: ["company_name", "user_name", "verification_code", "verify_url"],
    enabled: true,
    lastUpdated: daysAgo(2),
  },
  {
    id: "tpl-4",
    name: "Two-Factor Authentication Code",
    type: "2fa_code",
    subject: "Your {{company_name}} Authentication Code",
    body: `Hi {{user_name}},

Your two-factor authentication code is:

{{2fa_code}}

This code expires in 10 minutes. Do not share this code with anyone.

If you didn't request this code, your account may be at risk. Please contact support immediately.

Best regards,
{{company_name}} Security`,
    variables: ["company_name", "user_name", "2fa_code"],
    enabled: true,
    lastUpdated: daysAgo(1),
  },
  {
    id: "tpl-5",
    name: "Login Alert",
    type: "login_alert",
    subject: "New Login Detected - {{company_name}}",
    body: `Hi {{user_name}},

We detected a new login to your account.

Login details:
- Time: {{login_time}}
- Location: {{login_location}}
- Device: {{login_device}}
- IP Address: {{login_ip}}

If this was you, no action is needed. If you don't recognize this activity, please change your password immediately and contact support.

Best regards,
{{company_name}} Security`,
    variables: ["company_name", "user_name", "login_time", "login_location", "login_device", "login_ip"],
    enabled: true,
    lastUpdated: daysAgo(4),
  },
  {
    id: "tpl-6",
    name: "Account Locked",
    type: "account_locked",
    subject: "Your Account Has Been Locked - {{company_name}}",
    body: `Hi {{user_name}},

Your {{company_name}} account has been temporarily locked due to multiple failed login attempts.

To unlock your account, please:
1. Wait {{lock_duration}} minutes, or
2. Click here to unlock immediately: {{unlock_url}}

If you believe this was not you, please contact our security team immediately.

Best regards,
{{company_name}} Security`,
    variables: ["company_name", "user_name", "lock_duration", "unlock_url"],
    enabled: false,
    lastUpdated: daysAgo(10),
  },
];
